
package Project;

//import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class GUI extends javax.swing.JFrame {

    private static final String url = "jdbc:postgresql://localhost:5432/ZardApartment";
    private static final String username="postgres";
    private static final String password="postgre";
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int n,p,id,delete;
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //===================Function====================\\
    public void getConnection(){
        /*Connection conn = null;*/
        try{
            Class.forName("org.postgresql.Driver");
            conn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/ZardApartment","postgres","postgre");
            
            pst = conn.prepareStatement("SELECT * FROM Tenants ");
            
            rs = pst.executeQuery();
           
           ResultSetMetaData stData = rs.getMetaData();
           
           n = stData.getColumnCount();
           
           DefaultTableModel RecordTable = (DefaultTableModel)jTable.getModel();
           RecordTable.setRowCount(0);
           
           while(rs.next()){
               Vector columnData = new Vector();
               
               for(p = 1;p <= n; p++){
                   columnData.add(rs.getString("clientID"));
                   columnData.add(rs.getString("clientName"));
                   columnData.add(rs.getString("phoneNumber"));
                   columnData.add(rs.getString("HouseNumber"));
                   
               }
               RecordTable.addRow(columnData);
           }
                      
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
        
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jtxtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtHouse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 69, 121), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 69, 121), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 170, 40));

        btnInsert.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 170, 40));

        btnUpdate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, 40));

        btnSelect.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnSelect.setText("SELECT");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        jPanel2.add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 170, 40));

        btnReset.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 170, 40));

        btnDelete1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnDelete1.setText("DELETE");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 270, 460));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 69, 121), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 69, 121), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 230, 340));

        jtxtName.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 290, 50));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setText("Client Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 40));

        jtxtPhone.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(jtxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 290, 50));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setText("Phone Number");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 161, 150, 30));

        jtxtId.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 37, 290, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setText("ID Number");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 40));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setText("House Number");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 40));

        jtxtHouse.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel3.add(jtxtHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 290, 50));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Number", "ClientName", "Phone Number", "House Number"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 580, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 680, 460));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 48)); // NOI18N
        jLabel1.setText("ZARD APARTMENT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 980, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed


        // TODO add your handling code here:
        try{
            Class.forName("org.postgresql.Driver");
            conn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/ZardApartment","postgres","postgre");
            
            int row = jTable.getSelectedRow();
            String value = (jTable.getModel().getValueAt(row, 0).toString());
            
            pst = conn.prepareStatement("UPDATE Tenants SET clientName = ?,phoneNumber=?,houseNumber=? where clientID="+value);
            
            
            
            pst.setString(1,jtxtId.getText());
            pst.setString(2,jtxtName.getText());
            pst.setString(3,jtxtPhone.getText());
            pst.setString(4,jtxtHouse.getText());
            
            pst.execute();
           JOptionPane.showMessageDialog(this, "Updated");
           getConnection();
            
         } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
             
         
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       frame = new JFrame ("Exit");
       if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Zard Apartment",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
       {
           System.exit(0);
       }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        
         try{
            Class.forName("org.postgresql.Driver");
            conn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/ZardApartment","postgres","postgre");
            pst = conn.prepareStatement("INSERT INTO Tenants (clientID,clientName,"+"phoneNumber,houseNumber) VALUES(?,?,?,?)");
            
            pst.setString(1,jtxtId.getText());
            pst.setString(2,jtxtName.getText());
            pst.setString(3,jtxtPhone.getText());
            pst.setString(4,jtxtHouse.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record has been added");
            getConnection();
            
         } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_btnInsertActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        try{
         Class.forName("org.postgresql.Driver");
         conn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/ZardApartment","postgres","postgre");
         pst = conn.prepareStatement("SELECT * FROM Tenants ");

         DefaultTableModel RecordTable = (DefaultTableModel)jTable.getModel();
         int SelectedRows= jTable.getSelectedRow();
           
           jtxtId.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
           jtxtName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
           jtxtPhone.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
           jtxtHouse.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
        



    }//GEN-LAST:event_jTableMouseClicked

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("org.postgresql.Driver");
            conn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/ZardApartment","postgres","postgre");
            
            pst = conn.prepareStatement("SELECT * FROM Tenants ");
            
            pst.setString(1,jtxtId.getText());
            pst.setString(2,jtxtName.getText());
            pst.setString(3,jtxtPhone.getText());
            pst.setString(4,jtxtHouse.getText());
            
            rs.last();
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record has been added");
            getConnection();
            
         } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
             
         
        
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        jtxtId.setText("");
        jtxtName.setText("");
        jtxtPhone.setText("");
        jtxtHouse.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void jtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable.getModel();
        int SelectedRows = jTable.getSelectedRow();
        try{
            id=Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            delete =JOptionPane.showConfirmDialog(null, "Confirm if you want to delete the item you have selected","Warning"
                    ,JOptionPane.YES_NO_OPTION);
            if(delete == JOptionPane.YES_OPTION)
            {
                Class.forName("org.postgresql.Driver");
                conn =DriverManager.getConnection("jdbc:postgresql://localhost:5432/ZardApartment","postgres","postgre");
            
                 pst = conn.prepareStatement("DELETE FROM Tenants WHERE clientID = ? ");
                 pst.setString(1, jtxtId.getText());
                
                 JOptionPane.showMessageDialog(null, " Deleted");
                
                 
                 jtxtId.requestFocus();
                 jtxtId.setText("");
                 jtxtName.setText("");
                 jtxtPhone.setText("");
                 jtxtHouse.setText("");
                 
                 pst.execute();    
            }
        }
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        getConnection();
    }//GEN-LAST:event_btnDelete1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jtxtHouse;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhone;
    // End of variables declaration//GEN-END:variables
}
